# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    env:
      platform: aws
      region: us-east-1
      account: 34221212

      USER_PG: ${{secrets.USER_PG}}
      HOST_PG: ${{secrets.HOST_PG}}
      PASSWORD_PG: ${{secrets.PASSWORD_PG}}
      DATABASE_PG: ${{secrets.DATABASE_PG}}
      PORT_PG: ${{secrets.PORT_PG}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "paso1: mostrar mensaje"
        run: 
          echo "Mensaje 1"
      - name: "paso2: mostrar mensaje2"
        run: 
          echo "Mensaje 2"
      - name: "paso3: mostrar variables de entorno"
        run: |
          echo "plataforma: ${{env.platform}}"
          echo "region: ${{env.region}}"
          echo "account: ${{env.account}}"
      - name: "paso4: mostrar variables por defecto"
        run: |
          echo "evento: ${{toJson(github.event)}}"
          echo "api url: ${{toJson(github.api_url)}}"
      - name: "paso5: mostrar mi variable, el host y la pas"
        run: |
          echo "mi host: ${{env.HOST_PG}}"
          echo "mi pass: ${{env.PASSWORD_PG}}"
      - name: "paso6: Ejecutar script de Node.js con secretos"
        run: node -e "console.log(process.env.HOST_PG)"
        env:
          # Asigna el secreto de GitHub a una variable de entorno llamada MI_SECRETO
          USER_PG: ${{secrets.USER_PG}}
          HOST_PG: ${{secrets.HOST_PG}}
          PASSWORD_PG: ${{secrets.PASSWORD_PG}}
          DATABASE_PG: ${{secrets.DATABASE_PG}}
          PORT_PG: ${{secrets.PORT_PG}}

      - name: "paso7: ahora si"
        run: node -e "console.log(process.env.HOST_PG)"
        env:
          # Asigna el secreto de GitHub a una variable de entorno llamada MI_SECRETO
          
          USER_PG: ${{secrets.USER_PG}}
          HOST_PG: ${{secrets.HOST_PG}}
          PASSWORD_PG: ${{secrets.PASSWORD_PG}}
          DATABASE_PG: ${{secrets.DATABASE_PG}}
          PORT_PG: ${{secrets.PORT_PG}}
       
      - name: "paso8: hacer un echo para las variables"
        run: |
          echo "mi host: ${{secrets.HOST_PG}}"
          echo "mi pass: ${{secrets.PASSWORD_PG}}"
          echo "mi user: ${{secrets.USER_PG}}"
          echo "mi database: ${{secrets.DATABASE_PG}}"
          echo "mi port: ${{secrets.PORT_PG}}"
        
        env:
          # Asigna el secreto de GitHub a una variable de entorno llamada MI_SECRETO
          
          USER_PG: ${{secrets.USER_PG}}
          HOST_PG: ${{secrets.HOST_PG}}
          PASSWORD_PG: ${{secrets.PASSWORD_PG}}
          DATABASE_PG: ${{secrets.DATABASE_PG}}
          PORT_PG: ${{secrets.PORT_PG}}

      
